#!/bin/sh

run_cmd() {
    echo "[-] $@"
    if ! "$@"; then
        echo "[!] $@ failed"
        exit 1
    fi
}

deploy() {
    (
        cd ~
        echo "[-] Deploying $1"
        run_cmd cd "$1"
        run_cmd git pull
        run_cmd docker-compose pull
        run_cmd docker-compose build
        run_cmd docker-compose up --detach
        echo "[+] Done"
    )
}

cd "$(dirname "$0")"

if [ ! -p data/fifo ]; then
    rm -f data/fifo
    mkfifo data/fifo
fi

while true; do
    read path < data/fifo
    if [ -n "$path" ]; then
        deploy "$path" >&2
    fi
done
