#!/bin/bash

log() {
    echo "$(date +'%F %T') $1"
}

run_cmd() {
    log "[-] $*"
    if ! "$@"; then
        log "[!] $* failed"
        exit 1
    fi
}

deploy() {
    (
        cd ~
        log "[-] Deploying $1"
        run_cmd cd "$1"
        run_cmd git pull
        run_cmd docker compose pull
        run_cmd docker compose build
        run_cmd docker compose up --detach
        log "[+] Done"
    )
}

cd "$(dirname "$0")"

if [[ $(id -u) = 0 ]]; then
    log "[-] Running as root"
    deploy_user=$(python3 -c 'import sys, json; print(json.load(sys.stdin)["deploy_user"])' < config.json)
    if [[ $? != 0 ]]; then
        log "[!] Failed to get deploy_user from config.json"
        exit 1
    fi
    log "[-] Switching to user $deploy_user"
    exec sudo -u "$deploy_user" "./$(basename "$0")"
fi

if [[ ! -p data/fifo ]]; then
    rm -f data/fifo
    mkfifo data/fifo
fi

while true; do
    read -r path < data/fifo
    if [[ -n "$path" ]]; then
        deploy "$path" >&2
    fi
done
