version: "3.7"

services:
  app:
    build: .
    image: deploy-webhook
    restart: always
    networks:
      - traefik
    volumes:
      - ./data:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.deploy-webhook.rule=Host(`webhooks.tyilo.com`)
      - traefik.http.services.deploy-webhook.loadbalancer.server.port=8000

  deployer:
    image: alpine
    restart: always
    command: nsenter -t 1 -m -u -n -i -- bash -c "exec $$(docker inspect deploy-webhook-app-1 --format '{{index .Config.Labels \"com.docker.compose.project.working_dir\"}}')/deploy-daemon"
    privileged: true
    pid: "host"

networks:
  traefik:
    external: true
