version: "3.7"

services:
  app:
    build: .
    image: deploy-webhook
    restart: always
    networks:
      - traefik
    volumes:
      - ./data:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.deploy-webhook.rule=Host(`webhooks.tyilo.com`)
      - traefik.http.services.deploy-webhook.loadbalancer.server.port=8000

  deployer:
    image: alpine
    restart: always
    command: nsenter -t 1 -m -u -n -i -- sudo -u tyilo /home/tyilo/deploy-webhook/deploy-daemon
    privileged: true
    pid: "host"

networks:
  traefik:
    external: true
